In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().parent

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

In [2]:
import numpy as np
import os
import torch
import pickle
import config

from sentence_transformers import SentenceTransformer,InputExample,losses

from torch.utils.data import DataLoader

from src.metric import *

/tmp/ipykernel_5833/4205643316.py:7: DeprecationWarning: Importing from 'sentence_transformers.losses' is deprecated and will be removed in a future version. Please use 'sentence_transformers.sentence_transformer.losses' instead.
  from sentence_transformers import SentenceTransformer,InputExample,losses

In [3]:
torch.set_float32_matmul_precision("high")

In [4]:
np.random.seed(config.SEED)
torch.manual_seed(config.SEED)
torch.cuda.manual_seed_all(config.SEED)

In [5]:
path=config.CLEANED_DATA_DIR

In [6]:
with open(os.path.join(path,'train_df.pkl'),'rb') as f:
    train_df=pickle.load(f)
    
with open(os.path.join(path,'val_df.pkl'),'rb') as f:
    val_df=pickle.load(f)
        
with open(os.path.join(path,'test_df.pkl'),'rb') as f:
    test_df=pickle.load(f)

In [7]:
bi_encoder= SentenceTransformer('sentence-transformers/all-MiniLM-L6-v2',device=config.device)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [8]:
BATCH_SIZE=config.BASELINE_BATCH_SIZE

In [9]:
g = torch.Generator()
g.manual_seed(config.SEED)

In [10]:
bi_train_examples=[
    InputExample(texts=[j,r],label=float(config.label_to_score[l]))
    for r,j,l in zip(train_df['resume_text'],train_df['job_description_text'],train_df['label'])
]

bi_train_dataloader=DataLoader(bi_train_examples,shuffle=True,batch_size=BATCH_SIZE)

bi_train_loss=losses.CoSENTLoss(bi_encoder)

In [11]:
val_resume_emb = bi_encoder.encode(val_df['resume_text'].tolist(),
                              batch_size=BATCH_SIZE,convert_to_tensor=True,
                              show_progress_bar=True)
val_jd_emb = bi_encoder.encode(val_df['job_description_text'].tolist(),
                              batch_size=BATCH_SIZE,convert_to_tensor=True,
                              show_progress_bar=True)

scores = torch.cosine_similarity(val_resume_emb,val_jd_emb).cpu().numpy()

metrics=model_evaluation(scores,val_df,'job_description_text')
print("Spearman:",metrics['spearman_score'])
print("Top-3 Accuracy:",metrics['topk_score'])
print("NDCG:",metrics['ndcg_val'])
print("MAP:",metrics['map_score'])
print("MRR:",metrics['mrr_score'])

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Spearman: 0.33707315568770985
Top-3 Accuracy: 1.0
NDCG: 0.6698497775737843
MAP: 0.763996419409418
MRR: 0.8370039682539682

In [12]:
model_save_path=os.path.join(config.BASELINE_MODEL_DIR,'bi_encoder_baseline')
os.makedirs(config.BASELINE_MODEL_DIR,exist_ok=True)

In [13]:
epochs = 4
best_score = float('-inf')
min_delta=0.01

print("\tTraining Phase")
for epoch in range(1, epochs + 1):
    print(f"Epoch: {epoch}----------")

    bi_encoder.fit(
        train_objectives=[(bi_train_dataloader, bi_train_loss)],
        epochs=1,
        warmup_steps=int(len(bi_train_dataloader) * epochs * 0.1),
        show_progress_bar=True
    )

    val_resume_emb=bi_encoder.encode(
        val_df['resume_text'].tolist(),
        batch_size=64,convert_to_tensor=True,show_progress_bar=False
    )
    val_jd_emb =bi_encoder.encode(
        val_df['job_description_text'].tolist(),
        batch_size=64,convert_to_tensor=True,show_progress_bar=False
    )

    scores = torch.cosine_similarity(val_resume_emb, val_jd_emb).cpu().numpy()

    metrics = model_evaluation(scores, val_df, 'job_description_text')

    print("NDCG:",metrics['ndcg_val'])
    print("MAP:",metrics['map_score'])

    final_score = 0.6*metrics['ndcg_val']+0.3*metrics['map_score']+0.1*metrics['mrr_score']

    if final_score>best_score+min_delta:
        best_score=final_score
        bi_encoder.save(model_save_path)

	Training Phase
Epoch: 1----------

Computing widget examples:   0%|          | 0/1 [00:00<?, ?example/s]

NDCG: 0.6887492606401059
MAP: 0.7806188615372163

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch: 2----------

NDCG: 0.7304800633847892
MAP: 0.8180790080432424

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch: 3----------

NDCG: 0.765076876209396
MAP: 0.8422521559279733

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Epoch: 4----------

NDCG: 0.7758380668407097
MAP: 0.8506450379840199

In [14]:
bi_encoder= SentenceTransformer(model_save_path,device=config.device)

Loading weights:   0%|          | 0/103 [00:00<?, ?it/s]

In [15]:
val_resume_emb = bi_encoder.encode(val_df['resume_text'].tolist(),
                              batch_size=BATCH_SIZE,convert_to_tensor=True,
                              show_progress_bar=True)
val_jd_emb = bi_encoder.encode(val_df['job_description_text'].tolist(),
                              batch_size=BATCH_SIZE,convert_to_tensor=True,
                              show_progress_bar=True)

scores = torch.cosine_similarity(val_resume_emb,val_jd_emb).cpu().numpy()

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

Batches:   0%|          | 0/19 [00:00<?, ?it/s]

In [16]:
metrics=model_evaluation(scores,val_df,'job_description_text')
print("Spearman:",metrics['spearman_score'])
print("Top-3 Accuracy:",metrics['topk_score'])
print("NDCG:",metrics['ndcg_val'])
print("MAP:",metrics['map_score'])
print("MRR:",metrics['mrr_score'])

Spearman: 0.5572673976794694
Top-3 Accuracy: 1.0
NDCG: 0.765076876209396
MAP: 0.8422521559279733
MRR: 0.8814484126984127

In [17]:
eval_df=val_df.copy()
eval_df['score']=scores
print("\nScore spread within groups:")
spreads = []
for jd, group in eval_df.groupby('job_description_text'):
    if len(group) > 1:
        spreads.append(group['score'].max() - group['score'].min())

print(f"Mean spread: {np.mean(spreads):.3f}")
print(f"% groups with spread < 0.1:"f"{(np.array(spreads) < 0.1).mean():.3f}")

Score spread within groups:
Mean spread: 0.225
% groups with spread < 0.1:0.074

In [18]:
false_neg = eval_df[(eval_df['label'] == 2) & (eval_df['score'] < -0.3)]

print(f"Good Fit resumes scoring below -0.3: {len(false_neg)}")
print("\nSample false_neg resumes:")

i=0
for jd,group in false_neg.groupby('jd_clean'):
    print("-"*100)
    print(f"JD: {jd[:200]}")
    for _,row in group.head(3).iterrows():
        print(f"Index:{row['index']}")
        print(f"Score: {row['score']:.3f}")
        print(f"Resume: {row['resume_text'][:300]}\n")
    i+=1
    if i==3:
        break

Good Fit resumes scoring below -0.3: 0

Sample false_neg resumes:

In [20]:
confused = eval_df[(eval_df['label'] == 1) & (eval_df['score'] < 1.2) & (eval_df['score'] > -0.1)]

print(f"confused predictions: {len(confused)}")
print("\nSample confused resumes:")

i=0
for jd,group in confused.groupby('jd_clean'):
    print("-"*100)
    print(f"JD: {jd[:200]}")
    for _,row in group.head(3).iterrows():
        print(f"Score: {row['score']:.3f}")
        print(f"Resume: {row['resume_text'][:300]}\n")
    i+=1
    if i==3:
        break

confused predictions: 285

Sample confused resumes:
----------------------------------------------------------------------------------------------------
JD:  experienced in salesforce industries communications cloud.certification a plus 10+ years in sfdc 5+ years of experience in telecom domain solutioning for quoteto cash architect software solutions usi
Score: 0.832
Resume: Professional SummaryBusiness Intelligence Consultant with a 10-year career in data warehousing, business intelligence reporting, and data management architecture. Progressive developer and technical team lead with a strength in design & development, as well as driving performance, reducing inefficie

Score: 0.798
Resume: SummaryExperienced Data Analyst who responds to shifting business needs and priorities in a systematic and effective way.  Excels at implementing operational assessments and conducting functional requirements analysis for businesses of all sized.  Committed to maintaining cutting edge technical skil

Score: 0.792
Resume: Professional SummaryExperienced healthcare operation Analyst with broad understanding of hospital operation, supply chain, clinical data,  CPT/HCPCS, ICD-9, DRG, APC, and Medicare and Medicaid procedures. Support necessary analytic data requirements and expert  in development of custom stastical ben

----------------------------------------------------------------------------------------------------
JD:  perform and generate reports on all routine tests and testing activities.  troubleshoot manufacturing & component problems to the lowest line replaceable unit  lru , and support during qualification
Score: 0.819
Resume: SummaryTo seek employment as a Project Engineer in my desired field ( Full time / Part Time)
HighlightsA competent Project Engineer with excellent communication, organization and co-ordination skills. Possessing a proven track record of preparing and executing project plans and programs, ensuring th

Score: 0.779
Resume: SummaryHighly motivated Sales Associate with extensive customer service and sales experience. Outgoing sales professional with track record of driving increased sales, improving buying experience and elevating company profile with target market.
Professional Experience05/2014toCurrentSoftware Engine

Score: 0.804
Resume: SummaryElectrical  Operation & Maintenance Engineer and dedicated team player with extensive knowledge of electrical engineering concepts and a creative aptitude for new product development.
HighlightsUsing all tools and having command on word, excel and PowerPointinterest:*Football, Cricket,*Readin

----------------------------------------------------------------------------------------------------
JD: a remote contract senior accountant job headquartered in milwaukee, wi is available through accelerate professional talent solutions. this role requires candidates to have 5+ years of accounting exper
Score: 0.788
Resume: Career FocusAccomplished and results oriented Investment professional with strong leadership and interpersonal skills who adds energy and value to an organization's quest for excellence.
Summary of SkillsInternet and Microsoft Office - MS Word, MS Power Point, MS Excel, Pivot Tables, Spreadsheets,Ma

Score: 0.786
Resume: SummarySkilled in high profile account management; knowledgeable in team building, oral and written presentation, and interpersonal communications; proven leadership skills in a cross-functional team environment; experienced on social media platforms; skilled in Microsoft Office Suite, Salesforce, G

Score: 0.808
Resume: Professional SummaryAccountant with more than 8 years accounting experience with profit making ,non for profit and non-governmental organizations (NGOs). Possess solid knowledge of GAAP, GASB and IFRS. Proficient in automated systems: such as QuickBooks, Sun system and Peachtree Accounting.
Core Qua

In [21]:
test_resume_emb=bi_encoder.encode(test_df['resume_text'].tolist(),
                              batch_size=BATCH_SIZE,convert_to_tensor=True,
                              show_progress_bar=True)
test_jd_emb = bi_encoder.encode(test_df['job_description_text'].tolist(),
                              batch_size=BATCH_SIZE,convert_to_tensor=True,
                              show_progress_bar=True)

scores = torch.cosine_similarity(test_resume_emb,test_jd_emb).cpu().numpy()

metrics=model_evaluation(scores,test_df,'job_description_text')

Batches:   0%|          | 0/28 [00:00<?, ?it/s]

Batches:   0%|          | 0/28 [00:00<?, ?it/s]

In [22]:
print("Spearman:",metrics['spearman_score'])
print("Top-3 Accuracy:",metrics['topk_score'])
print("NDCG:",metrics['ndcg_val'])
print("MAP:",metrics['map_score'])
print("MRR:",metrics['mrr_score'])

Spearman: 0.3918299704926086
Top-3 Accuracy: 1.0
NDCG: 0.6470203998041301
MAP: 0.7479806457300369
MRR: 0.7726971116315378